import streamlit as st

with st.empty():
    st.write('1 – Objetivo\nPara a BELLOCARD – Administradora de Cartões LTDA, a privacidade e segurança são\nprioridades e nos comprometemos com a transparência do tratamento de dados pessoais dos\nossos usuários/clientes. Por isso, está presente Política de Privacidade estabelece como regras e\npadrões de como é feita a coleta, uso e transferência de informações de clientes ou outras pessoas\nque acessam ou usam nossas aplicações.')  # Closing quotation mark added here
with st.empty():
    st.write('Ao utilizar nossos serviços, você entende que coletaremos e usaremos suas informações\npessoais nas formas descritas nesta Política, sob as normas da Constituição Federal de 1988 (art. 5º,\nLXXIX; e o art. 22º, XXX – incluídos pela EC 115/2022), das normas de Proteção de Dados (LGPD, Lei\nFederal 13.709/2018), das disposições consumeristas da Lei Federal 8078/1990 e as demais normas\ndo ordenamento jurídico brasileiro aplicáveis.\nDessa forma, a BELLOCARD – Administradora de Cartões LTDA, doravante denominada\nBELLOCARD, inscrita no CNPJ/MF sob o nº 33.735.789/0001-88, no papel de Controladora de Dados,\nobriga-se ao disposto na presente Política de Privacidade.')  # Closing quotation mark added here
    st.write('\n\n2. Dados Coletados\n\nNossas aplicações coletam e utilizam dados pessoais e/ou empresariais de seus\nclientes/associados, lojistas, sindicatos e empresas, de forma a viabilizar a prestação de serviços.\n2.1. Dados fornecidos pelos Clientes/Associados\nEndereço completo, nome completo, nome da mãe, nome do pai, salário, dados bancários\n(banco, agência e conta), telefone fixo e celular, título de eleitor, zona e seção, empresa que\ntrabalha, data de admissão e data de demissão.\n2.2. Dados fornecidos pelos Lojistas\nEndereço Completo, Razão Social, Nome Fantasia, Telefone fixo, Celular e Fax, e-mail,\natividade do Lojista, Informações Bancárias (banco, agência, conta e Chave PIX).\n2.3. Dados fornecidos pelos Sindicatos\nEndereço Completo, Razão Social, Nome Fantasia, Telefone fixo, Celular e Fax, e-mail.\n2.4. Dados fornecidos pelos Empresas\nEndereço Completo, Razão Social, Nome Fantasia, CNPJ, Telefone fixo, Celular e Fax, e-mail.\n2.5. Informação coletadas pelas nossas aplicações WEB e Aplicativos\nAs informações coletadas pelos nossos aplicativos e aplicações incluirão todas ou apenas\nalgumas das abaixo descritas, dependendo de quais e como você optar por usar.\n\n\na) Geolocalização e Endereço IP – Informações detalhadas sobre a geolocalização, sob a\nforma de sinais GPS, endereço IP e outras informações relacionadas enviadas pelo dispositivo móvel\nno qual o aplicativo está instalado e ativado;\nb) Detalhes do Aparelho – Informações de status de bateria, modelo do aparelho, sistema\noperacional e versão utilizados, apps instalados e tipo de conexão utilizada (rede móvel de dados\nou wi-fi);\nc) Android Device ID – Identificador único que cada aparelho com sistema operacional\nAndroid possui;\nd) Dados de acesso – Para fins exclusivos de permitir o acesso aos serviços relacionados\ndo Google, os apps poderão solicitar dados de acesso à conta Google vinculada ao app.')  # Closing quotation mark added here
    st.write('poderá ser identificado unicamente para que as informações possam ser enviadas aos nossos') 
    st.write('servidores e retornadas corretamente para o seu aparelho e aplicativo.') 
    st.write('3.2 – Uso na Aplicação WEB') 
    st.write('Os dados são coletados exclusivamente utilizados para manter o correto funcionamento') 
    st.write('da aplicação.') 
    st.write('3.3 – Outros') 
    st.write('Alguns dos dados fornecidos já citados nessa política poderão também vir a ser utilizados') 
    st.write('exclusivamente para auditoria e análise interna, para nos ajudar a desenvolver, melhorar nossos') 
    st.write('serviços e conteúdos disponibilizados.') 
    st.write('4. Base de Dados') 
    st.write('4.1 – Banco de Dados do Aplicativo') 
    st.write('As informações inseridas pelos usuários são para uso exclusivo em nossos aplicativos e') 
    st.write('são armazenadas em banco de dados local no seu aparelho e após a desinstalação do aplicativo as') 
    st.write('informações são apagadas. Contudo, ressaltamos que sua conta do Google pode possuir') 
    st.write('Configurações de backup automático de alguns desses dados por você informados. Se por ventura') 
    st.write('você não deseje realizar o backup automático desses dados, você poderá desativar essa') 
    st.write('funcionalidade manualmente nas configurações do seu sistema Android ou acessando suas') 
    st.write('configurações de conta.') 
    st.write('4.2 – Banco de Dados da Aplicação WEB') 
    st.write('As informações inseridas pelos colaboradores são para uso exclusivo em nossa aplicação') 
    st.write('e são armazenadas em bancos de dados em nosso parque tecnológico com acesso exclusivo apenas') 
    st.write('por nossos técnicos.') 
    st.write('5. Consentimento') 
    st.write('É a partir do consentimento do usuário do aplicativo e/ou aplicação BelloCard que tratamos') 
    st.write('os seus dados pessoais. O consentimento é a manifestação livre, informada e inequívoca pela qual') 
    st.write('você autoriza a BELLOCARD a tratar seus dados.') 
    st.write('Assim, em consonância com a Lei Geral de Proteção de Dados, seus dados só serão') 
    st.write('coletados, tratados e armazenados mediante prévio e expresso consentimento.') 
    st.write('O seu consentimento será obtido de forma específica para cada finalidade acima descrita,') 
    st.write('evidenciando o compromisso de transparência e boa-fé da BelloCard para com seus') 
    st.write('usuários/clientes, seguindo as regulações legislativas pertinentes.') 
    st.write('Ao utilizar os serviços da BelloCard e fornecer seus dados pessoais, você está ciente e') 
    st.write('consentindo com as disposições desta Política de Privacidade, além de conhecer seus direitos e') 
    st.write('como exercê-los.') 
    st.write('A qualquer tempo e sem nenhum custo, você poderá revogar seu consentimento.') 
    st.write('É importante destacar que a revogação do consentimento para o tratamento dos dados') 
    st.write('pode implicar a impossibilidade da performance adequada de alguma funcionalidade do site que') 
    st.write('dependa da operação. Tais consequências serão informadas previamente.') 
    st.write('6. Quais são os seus direitos?') 
    st.write('A BELLOCARD assegura a seus usuários/clientes seus direitos de titular previstos no artigo') 
    st.write('18 da Lei Geral de Proteção de Dados. Dessa forma, você pode, de maneira gratuita e a qualquer') 
    st.write('tempo:') 
    st.write('a. Confirmar a existência de tratamento de dados, de maneira simplificada ou em formato') 
    st.write('claro e completo, mediante solicitação ao nosso suporte.') 
    st.write('b. Acessar seus dados, podendo solicitá-los em uma cópia legível sob forma impressa ou') 
    st.write('por meio eletrônico, seguro e idôneo.') 
    st.write('c. Corrigir seus dados, ao solicitar a edição, correção ou atualização destes.') 
    st.write('d. Limitar seus dados quando desnecessários, excessivos ou tratados em') 
    st.write('desconformidade com a legislação através da anonimização, bloqueio ou eliminação.') 
    st.write('e. Solicitar a portabilidade de seus dados, através de um relatório de dados cadastrais que') 
    st.write('a BELLOCARD trata a seu respeito.') 
    st.write('f. Eliminar seus dados tratados a partir de seu consentimento, exceto nos casos previstos') 
    st.write('em lei.') 
    st.write('g. Revogar seu consentimento, desautorizando o tratamento de seus dados.') 
    st.write('h. Informar-se sobre a possibilidade de não fornecer seu consentimento e sobre as') 
    st.write('consequências da negativa.') 
    st.write('7. Como você pode exercer seus direitos?') 
    st.write('Para exercer seus direitos de titular, você deve entrar em contato com a (nome empresarial') 
    st.write('simplificado) através dos seguintes meios disponíveis:') 
    st.write('• E-mail: <a href="mailto:adm@bellocard.com.br">adm@bellocard.com.br</a>') 
    st.write('• Telefones: (67) 3326-6510 | (67) 9 9892-9178') 
    st.write('De forma a garantir a sua correta identificação como titular dos dados pessoais objeto da') 
    st.write('solicitação, é possível que solicitemos documentos ou demais comprovações que possam') 
    st.write('comprovar sua identidade. Nessa hipótese, você será informado previamente.') 
    st.write('8. Como e por quanto tempo seus dados serão') 
    st.write('armazenados?') 
    st.write('Seus dados pessoais coletados pela BELLOCARD serão utilizados e armazenados durante o') 
    st.write('tempo necessário para a prestação do serviço ou para que as finalidades elencadas na presente') 
    st.write('Política de Privacidade sejam atingidas, considerando os direitos dos titulares dos dados e dos') 
    st.write('controladores.') 
    st.write('De modo geral, seus dados serão mantidos enquanto a relação contratual entre você e') 
    st.write('a BELLOCARD perdurar. Findado o período de armazenamento dos dados pessoais, estes serão') 
    st.write('excluídos de nossas bases de dados ou anonimizados, ressalvadas as hipóteses legalmente previstas') 
    st.write('no artigo 16 lei geral de proteção de dados, a saber:') 
    st.write('I – Cumprimento de obrigação legal ou regulatória pelo controlador;') 
    st.write('II – Estudo por órgão de pesquisa, garantida, sempre que possível, a anonimização dos dados') 
    st.write('pessoais;') 
    st.write('III – Transferência a terceiro, desde que respeitados os requisitos de tratamento de dados') 
    st.write('dispostos nesta Lei; ou') 
    st.write('IV – Uso exclusivo do controlador, vedado seu acesso por terceiro, e desde que anonimizados') 
    st.write('os dados.') 
    st.write('Isto é, informações pessoais sobre você que sejam imprescindíveis para o cumprimento de') 
    st.write('determinações legais, judiciais e administrativas e/ou para o exercício do direito de defesa em') 
    st.write('processos judiciais e administrativos serão mantidas, a despeito da exclusão dos demais dados.') 
    st.write('O armazenamento de dados coletados pela BELLOCARD reflete o nosso compromisso com a') 
    st.write('segurança e privacidade dos seus dados. Empregamos medidas e soluções técnicas de proteção') 
    st.write('aptas a garantir a confidencialidade, integridade e inviolabilidade dos seus dados. Além disso,') 
    st.write('também contamos com medidas de segurança apropriadas aos riscos e com controle de acesso às') 
    st.write('informações armazenadas.') 
    st.write('9. O que fazemos para manter seus dados seguros?') 
    st.write('Para mantermos suas informações pessoais seguras, usamos ferramentas físicas, eletrônicas') 
    st.write('e gerenciais orientadas para a proteção da sua privacidade.') 
    st.write('Aplicamos essas ferramentas levando em consideração a natureza dos dados pessoais') 
    st.write('coletados, o contexto e a finalidade do tratamento e os riscos que eventuais violações gerariam para') 
    st.write('os direitos e liberdades do titular dos dados coletados e tratados.') 
    st.write('Entre as medidas que adotamos, destacamos as seguintes:') 
    st.write('a. Apenas pessoas autorizadas têm acesso a seus dados pessoais') 
    st.write('b. O acesso a seus dados pessoais é feito somente após o compromisso de') 
    st.write('confidencialidade') 
    st.write('c. Seus dados pessoais são armazenados em ambiente seguro e idôneo.') 
    st.write('A BELLOCARD se compromete a adotar as melhores posturas para evitar incidentes de') 
    st.write('segurança. Contudo, é necessário destacar que nenhuma página virtual é inteiramente segura e') 
    st.write('livre de riscos. É possível que, apesar de todos os nossos protocolos de segurança, problemas de') 
    st.write('culpa exclusivamente de terceiros ocorram, como ataques cibernéticos de hackers, ou também em') 
    st.write('decorrência da negligência ou imprudência do próprio usuário/cliente.') 
    st.write('Em caso de incidentes de segurança que possa gerar risco ou dano relevante para você ou') 
    st.write('qualquer um de nossos usuários/clientes, comunicaremos aos afetados e a Autoridade Nacional de') 
    st.write('Proteção de Dados sobre o ocorrido, em consonância com as disposições da Lei Geral de Proteção') 
    st.write('de Dados.') 
    st.write('10. Cookies ou dados de navegação') 
    st.write('A BELLOCARD faz uso de Cookies, que são arquivos de texto enviados pela plataforma ao seu') 
    st.write('computador e que nele se armazenam, que contém informações relacionadas à navegação do site.') 
    st.write('Em suma, os Cookies são utilizados para aprimorar a experiência de uso.') 
    st.write('Ao acessar nosso site e consentir com o uso de Cookies, você manifesta conhecer e aceitar') 
    st.write('a utilização de um sistema de coleta de dados de navegação com o uso de Cookies em seu') 
    st.write('dispositivo.') 
    st.write('Você pode, a qualquer tempo e sem nenhum custo, alterar as permissões, bloquear ou') 
    st.write('recusar os Cookies. Todavia, a revogação do consentimento de determinados Cookies pode') 
    st.write('inviabilizar o funcionamento correto de alguns recursos da plataforma.') 
    st.write('Para gerenciar os cookies do seu navegador, basta fazê-lo diretamente nas configurações do') 
    st.write('navegador, na área de gestão de Cookies. Você pode acessar tutoriais sobre o tema diretamente') 
    st.write('nos links abaixo:') 
    st.write('<a href="https://support.microsoft.com/pt-br/windows/excluir-e-gerenciar-cookies-168dab11-0753-043d-7c16-ede5947fc64d">Se você usa o Internet Explorer.</a>') 
    st.write('<a href="https://support.mozilla.org/pt-BR/kb/gerencie-configuracoes-de-armazenamento-local-de-s">Se você usa o Firefox.</a>') 
    st.write('<a href="https://support.apple.com/pt-br/guide/safari/sfri11471/mac">Se você usa o Safari.</a>') 
    st.write('<a href="https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&oco=1&hl=pt-BR">Se você usa o Google Chrome.</a>') 
    st.write('<a href="https://support.microsoft.com/pt-br/microsoft-edge/excluir-cookies-no-microsoft-edge-63947406-40ac-c3b8-57b9-2a946a29ae09">Se você usa o Microsoft Edge.</a>') 
    st.write('<a href="https://help.opera.com/en/latest/web-preferences/#cookies">Se você usa o Opera.</a>') 
    st.write('11. Alteração desta Política de Privacidade') 
    st.write('Reservamos o direito de modificar essa Política de Privacidade a qualquer tempo,') 
    st.write('principalmente em função da adequação a eventuais alterações feitas em nosso aplicativo e/ou') 
    st.write('aplicação ou em âmbito legislativo. Recomendamos que você a revise com frequência.') 
    st.write('Eventuais alterações entrarão em vigor a partir de sua publicação em nosso site e sempre') 
    st.write('lhe notificaremos acerca das mudanças ocorridas.') 
    st.write('Ao utilizar nossos serviços e fornecer seus dados pessoais após tais modificações, você as') 
    st.write('consente.') 
    st.write('12. Responsabilidade') 
    st.write('A BELLOCARD prevê a responsabilidade dos agentes que atuam nos processos de') 
    st.write('tratamento de dados, em conformidade com os artigos 42 ao 45 da Lei Geral de Proteção de Dados.') 
    st.write('Nos comprometemos em manter esta Política de Privacidade atualizada, observando suas') 
    st.write('disposições e zelando por seu cumprimento.') 
    st.write('Além disso, também assumimos o compromisso de buscar condições técnicas e organizativas') 
    st.write('seguramente aptas a proteger todo o processo de tratamento de dados.') 
    st.write('Caso a Autoridade Nacional de Proteção de Dados exija a adoção de providências em relação') 
    st.write('ao tratamento de dados realizado pela BELLOCARD, comprometemo-nos a segui-las.') 
    st.write('12.1 Isenção de responsabilidade') 
    st.write('Conforme mencionado no Tópico 9, embora adotemos elevados padrões de segurança a fim') 
    st.write('de evitar incidentes, não há nenhuma página virtual inteiramente livre de riscos. Nesse sentido,') 
    st.write('a BELLOCARD não se responsabiliza por:') 
    st.write('I – Quaisquer consequências decorrentes da negligência, imprudência ou imperícia dos') 
    st.write('usuários em relação a seus dados individuais. Garantimos e nos responsabilizamos apenas pela') 
    st.write('segurança dos processos de tratamento de dados e do cumprimento das finalidades descritas no') 
    st.write('presente instrumento.') 
    st.write('Destacamos que a responsabilidade em relação à confidencialidade dos dados de acesso é') 
    st.write('do usuário.') 
    st.write('II – Ações maliciosas de terceiros, como ataques de hackers, exceto se comprovada conduta') 
    st.write('culposa ou deliberada da BELLOCARD.') 
    st.write('Destacamos que em caso de incidentes de segurança que possam gerar risco ou dano') 
    st.write('relevante para você ou qualquer um de nossos usuários/clientes, comunicaremos aos afetados e a') 
    st.write('Autoridade Nacional de Proteção de Dados sobre o ocorrido e cumpriremos as providências') 
    st.write('necessárias.') 
    st.write('III – Inveracidade das informações inseridas pelo usuário/cliente nos registros necessários') 
    st.write('para a utilização dos serviços da BELLOCARD; quaisquer consequências decorrentes de informações') 
    st.write('falsas ou inseridas de má-fé são de inteiramente responsabilidade do usuário/cliente.') 
    st.write('13. Encarregado de Proteção de Dados') 
    st.write('A BELLOCARD disponibiliza os seguintes meios para que você possa entrar em contato') 
    st.write('conosco para exercer seus direitos de titular:') 
    st.write('• E-mail: <a href="mailto:adm@bellocard.com.br">adm@bellocard.com.br</a>') 
    st.write('• Telefones: (67) 3326-6510 | (67) 9 9892-9178') 
    st.write('Caso tenha dúvidas sobre esta Política de Privacidade ou sobre os dados pessoais que') 
    st.write('armazenamos, você pode entrar em contato com o nosso Suporte através dos contatos acima') 
with st.empty():
    st.write('mencionados.') 
with st.empty():
    st.write('Campo Grande/MS, 03 de agosto de 2022.') 
